language: python
dist: bionic
env:
  - TEST_SUITE=jenkins
  - TEST_SUITE=harvest
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
python:
  - "3.6"
before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
before_install:
  - pip install --upgrade setuptools pip wheel
script:
  - make $TEST_SUITE
