name: build-and-test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build with Makefile
        run: make jenkins
      - name: Run Integration Tests
        run: make harvest  
