name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build with Makefile
        run: make jenkins
      - name: Run Integration Tests
        run: make harvest  
